Feat/dave 205 gesamtauswertungen ausgabe excel
it-at-m/dave-frontend pull request #231
Opened 2024-11-18 11:46 UTC by Der-Alex-K

Gesamtauswertung angebunden und Ergebnis ist als Excel downloadbar

2024-11-18 13:27 UTC, boal requested changes

2024-11-18 13:27 UTC, boal commented on frontend/src/api/service/FetchService.ts
> +    dataToSave: any,
Was ist der Datentyp von `dataToSave`?

Es deutet darauf hin, dass man alles hinschicken kann, diese Information irgendwo gespeichert wird und ein PDF zurückkommt.

2024-11-18 13:27 UTC, boal commented on frontend/src/api/service/FetchService.ts
> +    dataToSave: any,
Was ist der Datentyp von `dataToSave`?

Es deutet darauf hin, dass man alles hinschicken kann, diese Information irgendwo gespeichert wird und ein Blob zurückkommt.

2024-11-18 13:27 UTC, boal commented on frontend/src/api/service/GeneratePdfService.ts
> +  static postPdfCustomFetchReport(data: FormData): Promise<Blob> {
Was ist denn ein Custom-Fetch-Report?

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +    const allMstIds: Array<string> = [];
Evtl mehr Streamen.

ToArray macht den Code resilienter gegen undefined und null und die Iteration mit Extraktion geschieht in einem Aufruf.

```ts
    const allMstIds: Array<string> = _.toArray(messstelleAuswertungIds).map((messstelleAuswertungId) => messstelleAuswertungId.mstId);


```

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +    const allMstIds: Array<string> = [];
Das toArray kann evtl auch bereits weiter oben ausgeführt werden.

![image](https://github.com/user-attachments/assets/8f969b9a-4e91-4aff-a840-2c8e21152afb)

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +  if (messstelleAuswertungIds.length === 1) {
Ist eine so exakte Unterscheidung  zwischen einer und mehrere mqids erforderlich.

Der Text könnte dann generischer geschrieben werden, was dann den Code vereinfacht.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +    auswertungOptions.value.messstelleAuswertungIds.length === 0 &&
Evtl durch `_.isEmpty(auswertungOptions.value.messstelleAuswertungIds)` ersetzen. Der Code wird resilienter gegen undefined/null.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +    auswertungOptions.value.messstelleAuswertungIds.length === 1 &&
toArray verwenden um den Code resilienter zu machen.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +    auswertungOptions.value.messstelleAuswertungIds[0].mqIds.length === 0 &&
_.head verwenden um den Code resilienter zu machen.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +    mst.messquerschnitte.forEach((mq) => {
Den Code mit streaming abbilden.

```ts
itm.mqIds =  _.toArray(mst.messquerschnitte).map((mq) => mq.mqId);

```

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +    auswertungOptions.value.messstelleAuswertungIds[0].mqIds.length !== 0 &&
Weshalb wird hier `!== 0` und in Zeile 217 `> 0` verwendet? Es handelt sich um die selbe Prüfung.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +        auswertungOptions.value.messstelleAuswertungIds.find(
Diese Logik evtl in eigene Methode auslagern und sprechend benennen.

2024-11-18 13:27 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +    const item = { mstId: mst.mstId, mqIds: [] } as MessstelleAuswertungIdDTO;
Die Methode evtl mit einem Stream darstellen. Somit reduziert sich der Code auf eine Zeile und eine Zweizeilige Logik reduziert sich auf eine Zeile.

Des Weiteren wird die JS-Engine interne Zuweisungs und Iterationslogik verwendet.

2024-11-19 08:06 UTC, Der-Alex-K commented on frontend/src/components/messstelle/gesamtauswertung/stepper/AuswertungStepper.vue
> +  if (messstelleAuswertungIds.length === 1) {
Der Text war eine Vorgabe vom Fachbereich. Hab es aber ein bisschen verkürzt

2024-11-19 08:49 UTC, boal submitted a review, later dismissed

2024-11-19 12:19 UTC, Der-Alex-K commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +    auswertungOptions.value.messstelleAuswertungIds.push(item);
Hab es angepasst und hoffentlich alle stellen erwischt wo es geht.

2024-11-19 12:31 UTC, boal requested changes

2024-11-19 12:31 UTC, boal commented on frontend/src/components/messstelle/gesamtauswertung/stepper/OrtStepContent.vue
> +      mst.messquerschnitte.map((mq) => {
Hier muss auch kein Push an den Array gemacht werden.
```ts
item.mqIds = mst.messquerschnitte.map((mq) => mq.mqId);

```

2024-11-19 12:40 UTC, boal approved these changes

2024-11-19 13:26 UTC, merged